CREATE TABLE IF NOT EXISTS `RelatorioTerceirizado` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Entrada` TEXT NULL,
  `Fornecedor` TEXT NULL,
  `Nr. nota` TEXT NULL,
  `Série` TEXT NULL,
  `Data emissão` TEXT NULL,
  `Data de Entrada` TEXT NULL,
  `Data 1º vencimento` TEXT NULL,
  `Tipo custo entrada` TEXT NULL,
  `Valor da nota` TEXT NULL,
  `Valor desconto` TEXT NULL,
  `Qtd. itens` TEXT NULL,
  `Valor produtos` TEXT NULL,
  `Total frete` TEXT NULL,
  `Volume total` TEXT NULL,
  `Peso total` TEXT NULL,
  `Outras desp.` TEXT NULL,
  `Total entradas` TEXT NULL,
  `Status` TEXT NULL,
  `Prazo médio` TEXT NULL,
  `Empresa` TEXT NULL,
  `Data do cadastro` TEXT NULL,
  `Total de IPI` TEXT NULL,
  `Base de ICMS` TEXT NULL,
  `Total ICMS` TEXT NULL,
  `Desp. extras` TEXT NULL,
  `Desp. extr. mad.` TEXT NULL,
  `Frete conhec.` TEXT NULL,
  `Desp. financ.` TEXT NULL,
  `Base de ST` TEXT NULL,
  `Total ST` TEXT NULL,
  `DARE guia` TEXT NULL,
  `DARE antecip.` TEXT NULL,
  `DARE 1566` TEXT NULL,
  `Serviços` TEXT NULL,
  `ISSQN` TEXT NULL,
  `Valor apropriar` TEXT NULL,
  `Valor custo oper.` TEXT NULL,
  `ISSQN retido` TEXT NULL,
  `Valor ICMS diferido` TEXT NULL,
  `Base FCP` TEXT NULL,
  `Valor FCP` TEXT NULL,
  `Base FCP ST` TEXT NULL,
  `Valor FCP ST` TEXT NULL,
  `Valor FEEF - MT` TEXT NULL,
  `ICMS desonerado` TEXT NULL,
  `ICMS descontado PIS/COFINS` TEXT NULL,
  `CFOP` TEXT NULL,
  `origemArquivo` VARCHAR(255) NULL,
  `importedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `dadosOriginaisJson` LONGTEXT NULL,
  INDEX `idx_relatorio_fornecedor` (`Fornecedor`(191)),
  INDEX `idx_relatorio_nf` (`Nr. nota`(191)),
  INDEX `idx_relatorio_status` (`Status`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
