CREATE TABLE IF NOT EXISTS AvaliacaoMotorista (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  agendamentoId INT NOT NULL,
  token VARCHAR(191) NOT NULL UNIQUE,
  protocolo VARCHAR(80) NULL,
  fornecedor VARCHAR(255) NULL,
  transportadora VARCHAR(255) NULL,
  motorista VARCHAR(255) NULL,
  cpfMotorista VARCHAR(32) NULL,
  placa VARCHAR(32) NULL,
  dataAgendada VARCHAR(32) NULL,
  horaAgendada VARCHAR(16) NULL,
  emailMotorista VARCHAR(255) NULL,
  atendimentoNota INT NULL,
  equipeNota INT NULL,
  rapidezNota INT NULL,
  processoTranquilo VARCHAR(32) NULL,
  comentario LONGTEXT NULL,
  respondeu TINYINT(1) NOT NULL DEFAULT 0,
  respondeuEm DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_avaliacao_motorista_agendamento (agendamentoId),
  INDEX idx_avaliacao_motorista_respondeu (respondeu)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
