CREATE TABLE IF NOT EXISTS `RelatorioTerceirizado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rowHash` VARCHAR(64) NOT NULL,
  `agendamentoId` INT NULL,
  `origemArquivo` VARCHAR(255) NULL,
  `Entrada` VARCHAR(50) NULL,
  `Fornecedor` VARCHAR(255) NULL,
  `Nr. nota` VARCHAR(80) NULL,
  `Série` VARCHAR(30) NULL,
  `Data emissão` DATE NULL,
  `Data de Entrada` DATE NULL,
  `Data 1º vencimento` DATE NULL,
  `Tipo custo entrada` VARCHAR(120) NULL,
  `Valor da nota` DECIMAL(15,2) NULL,
  `Valor desconto` DECIMAL(15,2) NULL,
  `Qtd. itens` INT NULL,
  `Valor produtos` DECIMAL(15,2) NULL,
  `Total frete` DECIMAL(15,2) NULL,
  `Volume total` DECIMAL(15,3) NULL,
  `Peso total` DECIMAL(15,3) NULL,
  `Outras desp.` DECIMAL(15,2) NULL,
  `Total entradas` DECIMAL(15,2) NULL,
  `Status` VARCHAR(80) NULL,
  `Prazo médio` VARCHAR(40) NULL,
  `Empresa` VARCHAR(120) NULL,
  `Data do cadastro` DATETIME NULL,
  `Total de IPI` DECIMAL(15,2) NULL,
  `Base de ICMS` DECIMAL(15,2) NULL,
  `Total ICMS` DECIMAL(15,2) NULL,
  `Desp. extras` DECIMAL(15,2) NULL,
  `Desp. extr. mad.` DECIMAL(15,2) NULL,
  `Frete conhec.` DECIMAL(15,2) NULL,
  `Desp. financ.` DECIMAL(15,2) NULL,
  `Base de ST` DECIMAL(15,2) NULL,
  `Total ST` DECIMAL(15,2) NULL,
  `DARE guia` DECIMAL(15,2) NULL,
  `DARE antecip.` DECIMAL(15,2) NULL,
  `DARE 1566` DECIMAL(15,2) NULL,
  `Serviços` DECIMAL(15,2) NULL,
  `ISSQN` DECIMAL(15,2) NULL,
  `Valor apropriar` DECIMAL(15,2) NULL,
  `Valor custo oper.` DECIMAL(15,2) NULL,
  `ISSQN retido` DECIMAL(15,2) NULL,
  `Valor ICMS diferido` DECIMAL(15,2) NULL,
  `Base FCP` DECIMAL(15,2) NULL,
  `Valor FCP` DECIMAL(15,2) NULL,
  `Base FCP ST` DECIMAL(15,2) NULL,
  `Valor FCP ST` DECIMAL(15,2) NULL,
  `Valor FEEF - MT` DECIMAL(15,2) NULL,
  `ICMS desonerado` DECIMAL(15,2) NULL,
  `ICMS descontado PIS/COFINS` DECIMAL(15,2) NULL,
  `CFOP` VARCHAR(20) NULL,
  `importedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_relatorio_rowhash` (`rowHash`),
  KEY `idx_relatorio_agendamento` (`agendamentoId`),
  KEY `idx_relatorio_fornecedor` (`Fornecedor`),
  KEY `idx_relatorio_nota` (`Nr. nota`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
